EX = {
"君":("君の名前は何ですか。","kimi no namae wa nan desu ka","你叫什么名字?"),
"僕":("僕は学生です。","boku wa gakusei desu","我是学生。"),
"もう":("もう寝る時間だ。","mou neru jikan da","已经到睡觉时间了。"),
"心":("心が温かくなった。","kokoro ga atatakaku natta","心里暖暖的。"),
"思い出 / 想い出":("旅行はいい思い出になった。","ryokou wa ii omoide ni natta","旅行成了美好的回忆。"),
"わかる":("この問題がわからない。","kono mondai ga wakaranai","这道题我不会。"),
"見る":("毎晩テレビを見る。","maiban terebi wo miru","每晚看电视。"),
"ただ":("ただ見ているだけです。","tada mite iru dake desu","只是看看而已。"),
"言葉":("日本語の言葉を覚える。","nihongo no kotoba wo oboeru","记日语单词。"),
"夏":("夏は海に行く。","natsu wa umi ni iku","夏天去海边。"),
"忘れる":("傘を忘れた。","kasa wo wasureta","忘带伞了。"),
"言う":("先生がそう言った。","sensei ga sou itta","老师是那么说的。"),
"夜":("夜はとても静かだ。","yoru wa totemo shizuka da","夜里很安静。"),
"全部":("全部食べた。","zenbu tabeta","全吃完了。"),
"人生":("人生は一度だけ。","jinsei wa ichido dake","人生只有一次。"),
"知る":("その話は知らない。","sono hanashi wa shiranai","我不知道那件事。"),
"歌":("この歌が好きだ。","kono uta ga suki da","我喜欢这首歌。"),
"顔":("顔が赤い。","kao ga akai","脸红了。"),
"笑う":("赤ちゃんが笑った。","akachan ga waratta","宝宝笑了。"),
"人":("あの人は誰?","ano hito wa dare","那个人是谁?"),
"このまま":("このまま真っすぐ行って。","konomama massugu itte","就这样一直往前走。"),
"一つ":("りんごを一つください。","ringo wo hitotsu kudasai","请给我一个苹果。"),
"目 / 眼":("目が疲れた。","me ga tsukareta","眼睛累了。"),
"書く":("名前を書いてください。","namae wo kaite kudasai","请写名字。"),
"胸":("胸がどきどきする。","mune ga dokidoki suru","心怦怦直跳。"),
"空":("今日は空が高い。","kyou wa sora ga takai","今天天高气爽。"),
"ずっと":("駅でずっと待っていた。","eki de zutto matte ita","在车站一直等着。"),
"消える / 消す":("電気を消して。","denki wo keshite","把灯关掉。"),
"花":("公園に花が咲いた。","kouen ni hana ga saita","公园里花开了。"),
"さよなら":("さよなら、また明日。","sayonara, mata ashita","再见,明天见。"),
"痛い":("お腹が痛い。","onaka ga itai","肚子疼。"),
"喉":("風邪で喉が痛い。","kaze de nodo ga itai","感冒了嗓子疼。"),
"詩":("彼は詩を書くのが好きだ。","kare wa shi wo kaku no ga suki da","他喜欢写诗。"),
"待つ":("駅で友達を待つ。","eki de tomodachi wo matsu","在车站等朋友。"),
"歩く":("毎朝駅まで歩く。","maiasa eki made aruku","每天早上走到车站。"),
"青":("青い服を買った。","aoi fuku wo katta","买了蓝色的衣服。"),
"歌う":("カラオケで歌う。","karaoke de utau","在KTV唱歌。"),
"遠く / 遠い":("家は駅から遠い。","ie wa eki kara tooi","家离车站很远。"),
"街":("夜の街は明るい。","yoru no machi wa akarui","夜晚的街道很亮。"),
"口":("口を大きく開けて。","kuchi wo ookiku akete","把嘴张大。"),
"生きる":("うちの猫は二十年生きた。","uchi no neko wa nijuunen ikita","我家的猫活了二十年。"),
"思う":("明日は晴れると思う。","ashita wa hareru to omou","我觉得明天会晴。"),
"音楽":("音楽を聴きながら勉強する。","ongaku wo kikinagara benkyou suru","边听音乐边学习。"),
"今日":("今日は月曜日だ。","kyou wa getsuyoubi da","今天是星期一。"),
"馬鹿":("馬鹿なことを言うな。","baka na koto wo iu na","别说傻话。"),
"描く":("猫の絵を描く。","neko no e wo egaku","画猫。"),
"風":("今日は風が強い。","kyou wa kaze ga tsuyoi","今天风很大。"),
"苦しい":("走ると息が苦しい。","hashiru to iki ga kurushii","一跑就喘不过气。"),
"雨":("雨が降っている。","ame ga futte iru","正在下雨。"),
"愛":("母の愛は大きい。","haha no ai wa ookii","母爱很伟大。"),
"どうでもいい":("色はどうでもいい。","iro wa doudemoii","颜色无所谓。"),
"触れる":("作品に触れないでください。","sakuhin ni furenaide kudasai","请勿触摸展品。"),
"流れる":("川がゆっくり流れる。","kawa ga yukkuri nagareru","河水缓缓流淌。"),
"残る":("仕事が少し残っている。","shigoto ga sukoshi nokotte iru","还剩一点工作。"),
"月明かり":("月明かりで道が見えた。","tsukiakari de michi ga mieta","借着月光看得见路。"),
"歌詞":("この曲の歌詞を覚えたい。","kono kyoku no kashi wo oboetai","想记住这首歌的歌词。"),
"眠る / 眠い":("赤ちゃんがぐっすり眠っている。","akachan ga gussuri nemutte iru","宝宝睡得很香。"),
"また":("また来てね。","mata kite ne","下次再来哦。"),
"雲":("白い雲が浮かんでいる。","shiroi kumo ga ukande iru","白云飘着。"),
"思い出す":("鍵の場所を思い出した。","kagi no basho wo omoidashita","想起钥匙放哪了。"),
"冷たい / 冷める":("スープが冷めた。","suupu ga sameta","汤凉了。"),
"本当":("本当にありがとう。","hontou ni arigatou","真的谢谢你。"),
"泳ぐ":("プールで泳ぐ。","puuru de oyogu","在泳池游泳。"),
"逃げる":("猫が逃げた。","neko ga nigeta","猫跑掉了。"),
"神様":("神様にお願いする。","kamisama ni onegai suru","向神明祈愿。"),
"嘘":("嘘をつかないで。","uso wo tsukanaide","别撒谎。"),
"聞く / 聴く":("ラジオを聴く。","rajio wo kiku","听收音机。"),
"どうせ":("どうせ間に合わない。","douse maniawanai","反正也来不及了。"),
"自分":("自分でやる。","jibun de yaru","自己来做。"),
"夕 / 夕陽":("夕陽がきれいだ。","yuuhi ga kirei da","夕阳很美。"),
"夢":("昨日変な夢を見た。","kinou hen na yume wo mita","昨天做了个怪梦。"),
"優しい":("彼女は優しい人だ。","kanojo wa yasashii hito da","她是个温柔的人。"),
"言い訳":("遅刻の言い訳をした。","chikoku no iiwake wo shita","为迟到找了借口。"),
"きっと":("きっと大丈夫だよ。","kitto daijoubu da yo","一定没问题的。"),
"価値":("この本は読む価値がある。","kono hon wa yomu kachi ga aru","这本书值得一读。"),
"昨日":("昨日は忙しかった。","kinou wa isogashikatta","昨天很忙。"),
"声":("大きい声で話して。","ookii koe de hanashite","大声点说。"),
"穴":("靴下に穴が開いた。","kutsushita ni ana ga aita","袜子破了个洞。"),
"考える":("よく考えてから決める。","yoku kangaete kara kimeru","好好想想再决定。"),
"揺れる":("地震で家が揺れた。","jishin de ie ga yureta","地震时房子晃了。"),
"透明":("透明なコップ。","toumei na koppu","透明的杯子。"),
"いらない":("袋はいらないです。","fukuro wa iranai desu","不需要袋子。"),
"世界":("世界を旅したい。","sekai wo tabi shitai","想环游世界。"),
"死ぬ":("水をやらないと花が死ぬ。","mizu wo yaranai to hana ga shinu","不浇水花会死。"),
"人間":("人間は考える動物だ。","ningen wa kangaeru doubutsu da","人是会思考的动物。"),
"踊る":("みんなで踊った。","minna de odotta","大家一起跳了舞。"),
"黙る":("彼は急に黙った。","kare wa kyuu ni damatta","他突然不说话了。"),
"辞める":("会社を辞めた。","kaisha wo yameta","辞职了。"),
"心臓":("試験の前は心臓がドキドキする。","shiken no mae wa shinzou ga dokidoki suru","考试前心脏怦怦跳。"),
"幸せ":("毎日幸せだ。","mainichi shiawase da","每天都很幸福。"),
"想像":("未来を想像する。","mirai wo souzou suru","想象未来。"),
"差す":("部屋に日が差す。","heya ni hi ga sasu","阳光照进房间。"),
"夜明け":("夜明けに出発する。","yoake ni shuppatsu suru","黎明时出发。"),
"綺麗":("部屋を綺麗にする。","heya wo kirei ni suru","把房间收拾干净。"),
"生活":("東京の生活に慣れた。","toukyou no seikatsu ni nareta","习惯了东京的生活。"),
"溢れる":("コップから水が溢れた。","koppu kara mizu ga afureta","水从杯子里溢出来了。"),
"浅い":("この川は浅い。","kono kawa wa asai","这条河很浅。"),
"指先":("冬は指先が冷たい。","fuyu wa yubisaki ga tsumetai","冬天指尖冰凉。"),
"明日":("明日また会おう。","ashita mata aou","明天再见吧。"),
"ギター":("兄はギターが上手だ。","ani wa gitaa ga jouzu da","哥哥吉他弹得很好。"),
"最低":("今日は最低の一日だった。","kyou wa saitei no ichinichi datta","今天是最糟糕的一天。"),
"まだ":("宿題がまだ終わっていない。","shukudai ga mada owatte inai","作业还没做完。"),
"涙":("映画を見て涙が出た。","eiga wo mite namida ga deta","看电影流泪了。"),
"褪せる":("古いシャツの色が褪せた。","furui shatsu no iro ga aseta","旧衬衫褪色了。"),
"群青":("群青色の絵の具を買った。","gunjouiro no enogu wo katta","买了群青色的颜料。"),
"藍":("藍で布を染める。","ai de nuno wo someru","用靛蓝染布。"),
"茜":("茜色の空。","akaneiro no sora","茜红色的天空。"),
"朝":("朝ご飯を食べる。","asagohan wo taberu","吃早饭。"),
"部屋":("部屋を掃除する。","heya wo souji suru","打扫房间。"),
"ロックンロール":("父はロックンロールが好きだ。","chichi wa rokkunrooru ga suki da","爸爸喜欢摇滚乐。"),
"マシンガン":("映画にマシンガンが出てきた。","eiga ni mashingan ga dete kita","电影里出现了机关枪。"),
"探す":("眼鏡を探している。","megane wo sagashite iru","在找眼镜。"),
"将来":("将来の夢は医者だ。","shourai no yume wa isha da","将来的梦想是当医生。"),
"六畳":("寝室は六畳だ。","shinshitsu wa rokujou da","卧室是六叠大小。"),
"窓":("窓を開けてください。","mado wo akete kudasai","请开窗。"),
"俯く":("恥ずかしくて俯いた。","hazukashikute utsumuita","害羞地低下了头。"),
"寝そべる":("ソファに寝そべって本を読む。","sofa ni nesobette hon wo yomu","趴在沙发上看书。"),
"隙間":("ドアの隙間から光が入る。","doa no sukima kara hikari ga hairu","光从门缝透进来。"),
"花緑青":("花緑青は昔の絵の具の名前だ。","hanarokushou wa mukashi no enogu no namae da","花绿青是一种旧时颜料的名字。"),
"国":("いろいろな国に行きたい。","iroiro na kuni ni ikitai","想去各种各样的国家。"),
"痛み":("足の痛みがなくなった。","ashi no itami ga nakunatta","脚不疼了。"),
"木漏れ日":("木漏れ日の中を散歩する。","komorebi no naka wo sanpo suru","在树影斑驳的阳光里散步。"),
"石畳":("古い石畳の道を歩く。","furui ishidatami no michi wo aruku","走在古老的石板路上。"),
"許す":("今回だけは許す。","konkai dake wa yurusu","就原谅这一次。"),
"大事":("大事な話がある。","daiji na hanashi ga aru","有重要的话要说。"),
}
